# Generated by Django 3.1.7 on 2021-04-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='lineitem_credits',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
