# Generated by Django 3.1.7 on 2021-04-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210404_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
